;; Tail-call dispatch torture test (regression guard for issue #1942).
;;
;; Without Wasmi's `portable-dispatch` feature, the operator dispatch relies on the operator handlers
;; being compiled as tail calls. A handler that fails to tail-call leaks one native stack frame per
;; execution; in a tight loop this accumulates and overflows the native stack (SIGABRT -> CI failure).
;;
;; Each exported `torture_*` function runs a tight `loop` whose body exercises a whole category of
;; Wasm operators. A Wasm `loop` keeps Wasmi's own value/call stack flat, so a non-tail-calling handler
;; in the body grows only the *native* stack. With a reduced `RUST_MIN_STACK` even a small per-op leak
;; overflows quickly. If every handler tail-calls correctly the loops complete and the asserts pass.
;;
;; NOTE: `memory.grow` and `table.grow` are deliberately excluded -- they are the known stable-only
;; residual non-tail handlers (see issue #1942). Add them here once they are made tail-callable.

(module
  (memory $mem 1)

  (table $t 8 funcref)
  (table $te 4 externref)

  (global $gi32 (mut i32) (i32.const 1))
  (global $gi64 (mut i64) (i64.const 1))
  (global $gf32 (mut f32) (f32.const 1))
  (global $gf64 (mut f64) (f64.const 1))
  (global $gv128 (mut v128) (v128.const i64x2 1 1))
  (global $gref (mut funcref) (ref.null func))
  (global $geref (mut externref) (ref.null extern))

  (data $passive "\00\01\02\03\04\05\06\07")
  (elem $epassive func $f0 $f1 $f2)
  (elem declare func $f0 $f1 $f2)
  (elem (table $t) (i32.const 0) func $f0 $f1 $f2)

  (type $unary (func (param i32) (result i32)))

  (func $f0 (param i32) (result i32) (local.get 0))
  (func $f1 (param i32) (result i32) (i32.add (local.get 0) (i32.const 1)))
  (func $f2 (param i32) (result i32) (i32.mul (local.get 0) (i32.const 2)))

  ;; ---- integer i32 ----------------------------------------------------------
  (func (export "torture_i32")
    (local $i i32) (local $x i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $x (i32.add (local.get $x) (local.get $x)))
      (local.set $x (i32.sub (local.get $x) (i32.const 7)))
      (local.set $x (i32.mul (local.get $x) (i32.const 3)))
      (local.set $x (i32.div_s (local.get $x) (i32.const 3)))
      (local.set $x (i32.div_u (local.get $x) (i32.const 3)))
      (local.set $x (i32.rem_s (local.get $x) (i32.const 7)))
      (local.set $x (i32.rem_u (local.get $x) (i32.const 7)))
      (local.set $x (i32.and (local.get $x) (i32.const 0xFF)))
      (local.set $x (i32.or (local.get $x) (i32.const 1)))
      (local.set $x (i32.xor (local.get $x) (i32.const 0x5A)))
      (local.set $x (i32.shl (local.get $x) (i32.const 1)))
      (local.set $x (i32.shr_s (local.get $x) (i32.const 1)))
      (local.set $x (i32.shr_u (local.get $x) (i32.const 1)))
      (local.set $x (i32.rotl (local.get $x) (i32.const 3)))
      (local.set $x (i32.rotr (local.get $x) (i32.const 3)))
      (local.set $x (i32.clz (local.get $x)))
      (local.set $x (i32.ctz (local.get $x)))
      (local.set $x (i32.popcnt (local.get $x)))
      (local.set $x (i32.eqz (local.get $x)))
      (local.set $x (i32.eq (local.get $x) (i32.const 0)))
      (local.set $x (i32.ne (local.get $x) (i32.const 1)))
      (local.set $x (i32.lt_s (local.get $x) (i32.const 5)))
      (local.set $x (i32.lt_u (local.get $x) (i32.const 5)))
      (local.set $x (i32.gt_s (local.get $x) (i32.const 5)))
      (local.set $x (i32.gt_u (local.get $x) (i32.const 5)))
      (local.set $x (i32.le_s (local.get $x) (i32.const 5)))
      (local.set $x (i32.le_u (local.get $x) (i32.const 5)))
      (local.set $x (i32.ge_s (local.get $x) (i32.const 5)))
      (local.set $x (i32.ge_u (local.get $x) (i32.const 5)))
      (local.set $x (i32.extend8_s (local.get $x)))
      (local.set $x (i32.extend16_s (local.get $x)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- integer i64 ----------------------------------------------------------
  (func (export "torture_i64")
    (local $i i32) (local $x i64) (local $c i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $x (i64.add (local.get $x) (local.get $x)))
      (local.set $x (i64.sub (local.get $x) (i64.const 7)))
      (local.set $x (i64.mul (local.get $x) (i64.const 3)))
      (local.set $x (i64.div_s (local.get $x) (i64.const 3)))
      (local.set $x (i64.div_u (local.get $x) (i64.const 3)))
      (local.set $x (i64.rem_s (local.get $x) (i64.const 7)))
      (local.set $x (i64.rem_u (local.get $x) (i64.const 7)))
      (local.set $x (i64.and (local.get $x) (i64.const 0xFF)))
      (local.set $x (i64.or (local.get $x) (i64.const 1)))
      (local.set $x (i64.xor (local.get $x) (i64.const 0x5A)))
      (local.set $x (i64.shl (local.get $x) (i64.const 1)))
      (local.set $x (i64.shr_s (local.get $x) (i64.const 1)))
      (local.set $x (i64.shr_u (local.get $x) (i64.const 1)))
      (local.set $x (i64.rotl (local.get $x) (i64.const 3)))
      (local.set $x (i64.rotr (local.get $x) (i64.const 3)))
      (local.set $x (i64.clz (local.get $x)))
      (local.set $x (i64.ctz (local.get $x)))
      (local.set $x (i64.popcnt (local.get $x)))
      (local.set $x (i64.extend8_s (local.get $x)))
      (local.set $x (i64.extend16_s (local.get $x)))
      (local.set $x (i64.extend32_s (local.get $x)))
      (local.set $c (i64.eqz (local.get $x)))
      (local.set $c (i64.eq (local.get $x) (i64.const 0)))
      (local.set $c (i64.ne (local.get $x) (i64.const 1)))
      (local.set $c (i64.lt_s (local.get $x) (i64.const 5)))
      (local.set $c (i64.lt_u (local.get $x) (i64.const 5)))
      (local.set $c (i64.gt_s (local.get $x) (i64.const 5)))
      (local.set $c (i64.gt_u (local.get $x) (i64.const 5)))
      (local.set $c (i64.le_s (local.get $x) (i64.const 5)))
      (local.set $c (i64.le_u (local.get $x) (i64.const 5)))
      (local.set $c (i64.ge_s (local.get $x) (i64.const 5)))
      (local.set $c (i64.ge_u (local.get $x) (i64.const 5)))
      (local.set $x (i64.extend_i32_s (local.get $c)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- float f32 ------------------------------------------------------------
  (func (export "torture_f32")
    (local $i i32) (local $x f32) (local $c i32)
    (local.set $i (i32.const 100000))
    (local.set $x (f32.const 3.14))
    (loop $l
      (local.set $x (f32.add (local.get $x) (f32.const 1)))
      (local.set $x (f32.sub (local.get $x) (f32.const 0.5)))
      (local.set $x (f32.mul (local.get $x) (f32.const 1.001)))
      (local.set $x (f32.div (local.get $x) (f32.const 1.7)))
      (local.set $x (f32.min (local.get $x) (f32.const 1e9)))
      (local.set $x (f32.max (local.get $x) (f32.const -1e9)))
      (local.set $x (f32.copysign (local.get $x) (f32.const 1)))
      (local.set $x (f32.abs (local.get $x)))
      (local.set $x (f32.neg (local.get $x)))
      (local.set $x (f32.ceil (local.get $x)))
      (local.set $x (f32.floor (local.get $x)))
      (local.set $x (f32.trunc (local.get $x)))
      (local.set $x (f32.nearest (local.get $x)))
      (local.set $x (f32.sqrt (f32.abs (local.get $x))))
      (local.set $c (f32.eq (local.get $x) (f32.const 0)))
      (local.set $c (f32.ne (local.get $x) (f32.const 1)))
      (local.set $c (f32.lt (local.get $x) (f32.const 5)))
      (local.set $c (f32.gt (local.get $x) (f32.const 5)))
      (local.set $c (f32.le (local.get $x) (f32.const 5)))
      (local.set $c (f32.ge (local.get $x) (f32.const 5)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- float f64 ------------------------------------------------------------
  (func (export "torture_f64")
    (local $i i32) (local $x f64) (local $c i32)
    (local.set $i (i32.const 100000))
    (local.set $x (f64.const 3.14))
    (loop $l
      (local.set $x (f64.add (local.get $x) (f64.const 1)))
      (local.set $x (f64.sub (local.get $x) (f64.const 0.5)))
      (local.set $x (f64.mul (local.get $x) (f64.const 1.001)))
      (local.set $x (f64.div (local.get $x) (f64.const 1.7)))
      (local.set $x (f64.min (local.get $x) (f64.const 1e9)))
      (local.set $x (f64.max (local.get $x) (f64.const -1e9)))
      (local.set $x (f64.copysign (local.get $x) (f64.const 1)))
      (local.set $x (f64.abs (local.get $x)))
      (local.set $x (f64.neg (local.get $x)))
      (local.set $x (f64.ceil (local.get $x)))
      (local.set $x (f64.floor (local.get $x)))
      (local.set $x (f64.trunc (local.get $x)))
      (local.set $x (f64.nearest (local.get $x)))
      (local.set $x (f64.sqrt (f64.abs (local.get $x))))
      (local.set $c (f64.eq (local.get $x) (f64.const 0)))
      (local.set $c (f64.ne (local.get $x) (f64.const 1)))
      (local.set $c (f64.lt (local.get $x) (f64.const 5)))
      (local.set $c (f64.gt (local.get $x) (f64.const 5)))
      (local.set $c (f64.le (local.get $x) (f64.const 5)))
      (local.set $c (f64.ge (local.get $x) (f64.const 5)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- conversions ----------------------------------------------------------
  (func (export "torture_conv")
    (local $i i32) (local $a i32) (local $b i64) (local $c f32) (local $d f64)
    (local.set $i (i32.const 100000))
    (local.set $c (f32.const 1.5))
    (local.set $d (f64.const 1.5))
    (loop $l
      (local.set $b (i64.extend_i32_s (local.get $a)))
      (local.set $b (i64.extend_i32_u (local.get $a)))
      (local.set $a (i32.wrap_i64 (local.get $b)))
      (local.set $c (f32.convert_i32_s (local.get $a)))
      (local.set $c (f32.convert_i32_u (local.get $a)))
      (local.set $c (f32.convert_i64_s (local.get $b)))
      (local.set $c (f32.convert_i64_u (local.get $b)))
      (local.set $d (f64.convert_i32_s (local.get $a)))
      (local.set $d (f64.convert_i32_u (local.get $a)))
      (local.set $d (f64.convert_i64_s (local.get $b)))
      (local.set $d (f64.convert_i64_u (local.get $b)))
      (local.set $c (f32.demote_f64 (local.get $d)))
      (local.set $d (f64.promote_f32 (local.get $c)))
      (local.set $a (i32.trunc_sat_f32_s (local.get $c)))
      (local.set $a (i32.trunc_sat_f32_u (local.get $c)))
      (local.set $a (i32.trunc_sat_f64_s (local.get $d)))
      (local.set $a (i32.trunc_sat_f64_u (local.get $d)))
      (local.set $b (i64.trunc_sat_f32_s (local.get $c)))
      (local.set $b (i64.trunc_sat_f32_u (local.get $c)))
      (local.set $b (i64.trunc_sat_f64_s (local.get $d)))
      (local.set $b (i64.trunc_sat_f64_u (local.get $d)))
      ;; `copysign(1.5, dynamic)` keeps these dynamic (so the handler is actually dispatched and not
      ;; constant-folded) while staying in range so the non-saturating truncations never trap.
      (local.set $a (i32.trunc_f32_s (f32.copysign (f32.const 1.5) (local.get $c))))
      (local.set $a (i32.trunc_f32_u (f32.copysign (f32.const 1.5) (local.get $c))))
      (local.set $a (i32.trunc_f64_s (f64.copysign (f64.const 1.5) (local.get $d))))
      (local.set $a (i32.trunc_f64_u (f64.copysign (f64.const 1.5) (local.get $d))))
      (local.set $b (i64.trunc_f32_s (f32.copysign (f32.const 1.5) (local.get $c))))
      (local.set $b (i64.trunc_f32_u (f32.copysign (f32.const 1.5) (local.get $c))))
      (local.set $b (i64.trunc_f64_s (f64.copysign (f64.const 1.5) (local.get $d))))
      (local.set $b (i64.trunc_f64_u (f64.copysign (f64.const 1.5) (local.get $d))))
      (local.set $a (i32.reinterpret_f32 (local.get $c)))
      (local.set $b (i64.reinterpret_f64 (local.get $d)))
      (local.set $c (f32.reinterpret_i32 (local.get $a)))
      (local.set $d (f64.reinterpret_i64 (local.get $b)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: loads ------------------------------------------------
  (func (export "torture_load")
    (local $i i32) (local $a i32) (local $b i64)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (i32.load (i32.const 16)))
      (local.set $a (i32.load8_s (i32.const 20)))
      (local.set $a (i32.load8_u (i32.const 20)))
      (local.set $a (i32.load16_s (i32.const 22)))
      (local.set $a (i32.load16_u (i32.const 22)))
      (local.set $b (i64.load (i32.const 32)))
      (local.set $b (i64.load8_s (i32.const 40)))
      (local.set $b (i64.load8_u (i32.const 40)))
      (local.set $b (i64.load16_s (i32.const 42)))
      (local.set $b (i64.load16_u (i32.const 42)))
      (local.set $b (i64.load32_s (i32.const 44)))
      (local.set $b (i64.load32_u (i32.const 44)))
      (drop (f32.load (i32.const 48)))
      (drop (f64.load (i32.const 56)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: stores -----------------------------------------------
  (func (export "torture_store")
    (local $i i32) (local $a i32) (local $b i64)
    (local.set $i (i32.const 100000))
    (loop $l
      (i32.store (i32.const 16) (local.get $a))
      (i32.store8 (i32.const 20) (local.get $a))
      (i32.store16 (i32.const 22) (local.get $a))
      (i64.store (i32.const 32) (local.get $b))
      (i64.store8 (i32.const 40) (local.get $b))
      (i64.store16 (i32.const 42) (local.get $b))
      (i64.store32 (i32.const 44) (local.get $b))
      (f32.store (i32.const 48) (f32.const 1))
      (f64.store (i32.const 56) (f64.const 1))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: size -------------------------------------------------
  (func (export "torture_memory_size")
    (local $i i32) (local $a i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (memory.size))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: copy -------------------------------------------------
  (func (export "torture_memory_copy")
    (local $i i32) (local $n i32)
    (local.set $i (i32.const 100000))
    (loop $l
      ;; dynamic length avoids the translator folding a constant-size bulk op.
      (local.set $n (i32.and (local.get $i) (i32.const 15)))
      (memory.copy (i32.const 64) (i32.const 0) (local.get $n))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: fill -------------------------------------------------
  (func (export "torture_memory_fill")
    (local $i i32) (local $n i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $n (i32.and (local.get $i) (i32.const 15)))
      (memory.fill (i32.const 80) (local.get $n) (local.get $n))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- linear memory: init + data.drop -------------------------------------
  (func (export "torture_memory_init")
    (local $i i32) (local $z i32)
    (local.set $i (i32.const 100000))
    (loop $l
      ;; dynamic-zero operands: dispatched (not const-folded) and valid even after `data.drop`.
      (memory.init $passive (local.get $z) (local.get $z) (local.get $z))
      (data.drop $passive)
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: get ----------------------------------------------------------
  (func (export "torture_table_get")
    (local $i i32) (local $r funcref) (local $e externref)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $r (table.get $t (i32.and (local.get $i) (i32.const 1))))
      (local.set $e (table.get $te (i32.and (local.get $i) (i32.const 1))))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: set ----------------------------------------------------------
  (func (export "torture_table_set")
    (local $i i32) (local $e externref)
    (local.set $i (i32.const 100000))
    (loop $l
      (table.set $t (i32.and (local.get $i) (i32.const 1)) (ref.func $f0))
      (table.set $te (i32.and (local.get $i) (i32.const 1)) (local.get $e))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: size ---------------------------------------------------------
  (func (export "torture_table_size")
    (local $i i32) (local $a i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (table.size $t))
      (local.set $a (table.size $te))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: copy ---------------------------------------------------------
  (func (export "torture_table_copy")
    (local $i i32) (local $n i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $n (i32.and (local.get $i) (i32.const 1)))
      (table.copy $t $t (i32.const 1) (i32.const 0) (local.get $n))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: fill ---------------------------------------------------------
  (func (export "torture_table_fill")
    (local $i i32) (local $n i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $n (i32.and (local.get $i) (i32.const 1)))
      (table.fill $t (i32.const 4) (ref.func $f1) (local.get $n))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tables: init + elem.drop --------------------------------------------
  (func (export "torture_table_init")
    (local $i i32) (local $z i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (table.init $t $epassive (local.get $z) (local.get $z) (local.get $z))
      (elem.drop $epassive)
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- reference ops --------------------------------------------------------
  (func (export "torture_ref")
    (local $i i32) (local $a i32) (local $r funcref) (local $e externref)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $r (ref.func $f2))
      (local.set $a (ref.is_null (local.get $r)))
      (local.set $r (ref.null func))
      (local.set $a (ref.is_null (local.get $r)))
      (local.set $e (ref.null extern))
      (local.set $a (ref.is_null (local.get $e)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- globals: get ---------------------------------------------------------
  (func (export "torture_global_get")
    (local $i i32) (local $a i32) (local $b i64) (local $c f32) (local $d f64)
    (local $v v128) (local $r funcref) (local $e externref)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (global.get $gi32))
      (local.set $b (global.get $gi64))
      (local.set $c (global.get $gf32))
      (local.set $d (global.get $gf64))
      (local.set $v (global.get $gv128))
      (local.set $r (global.get $gref))
      (local.set $e (global.get $geref))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- globals: set ---------------------------------------------------------
  (func (export "torture_global_set")
    (local $i i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (global.set $gi32 (local.get $i))
      (global.set $gi64 (i64.extend_i32_s (local.get $i)))
      (global.set $gf32 (f32.convert_i32_s (local.get $i)))
      (global.set $gf64 (f64.convert_i32_s (local.get $i)))
      (global.set $gv128 (i32x4.splat (local.get $i)))
      (global.set $gref (ref.func $f0))
      (global.set $geref (ref.null extern))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- parametric + variable ops -------------------------------------------
  (func (export "torture_param_var")
    (local $i i32) (local $a i32) (local $r funcref)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (select (local.get $i) (local.get $a) (local.get $a)))
      (local.set $r (select (result funcref) (ref.func $f0) (ref.null func) (local.get $a)))
      (local.tee $a (i32.add (local.get $a) (i32.const 1)))
      (drop)
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- direct calls ---------------------------------------------------------
  (func (export "torture_call")
    (local $i i32) (local $a i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (call $f0 (local.get $a)))
      (local.set $a (call $f1 (local.get $a)))
      (local.set $a (call $f2 (local.get $a)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- indirect calls -------------------------------------------------------
  (func (export "torture_call_indirect")
    (local $i i32) (local $a i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (local.set $a (call_indirect $t (type $unary) (local.get $a) (i32.const 0)))
      (local.set $a (call_indirect $t (type $unary) (local.get $a) (i32.const 1)))
      (local.set $a
        (call_indirect $t (type $unary) (local.get $a) (i32.and (local.get $i) (i32.const 1))))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- br_table -------------------------------------------------------------
  (func (export "torture_br_table")
    (local $i i32)
    (local.set $i (i32.const 100000))
    (loop $l
      (block $b0 (block $b1 (block $b2
        (br_table $b0 $b1 $b2 (i32.and (local.get $i) (i32.const 1)))
      )))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- tail calls: self-recursive counting (stays flat in Wasmi's stack) ----
  (func $count_rc (export "torture_return_call") (param $n i32)
    (if (local.get $n)
      (then (return_call $count_rc (i32.sub (local.get $n) (i32.const 1))))
    )
  )
  (func $count_rci (export "torture_return_call_indirect") (param $n i32) (result i32)
    (if (result i32) (local.get $n)
      (then
        (return_call_indirect $t (type $unary)
          (i32.sub (local.get $n) (i32.const 1))
          (i32.const 3)))
      (else (i32.const 0))
    )
  )
  (func $count_rci_target (param $n i32) (result i32)
    (return_call $count_rci (local.get $n))
  )
  (elem (table $t) (i32.const 3) func $count_rci_target)

  ;; ---- SIMD: integer lanes --------------------------------------------------
  (func (export "torture_simd_int")
    (local $i i32) (local $v v128) (local $s i32)
    (local.set $i (i32.const 50000))
    (local.set $v (v128.const i32x4 1 2 3 4))
    (loop $l
      ;; i8x16
      (local.set $v (i8x16.add (local.get $v) (local.get $v)))
      (local.set $v (i8x16.sub (local.get $v) (local.get $v)))
      (local.set $v (i8x16.add_sat_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.add_sat_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.sub_sat_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.sub_sat_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.min_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.min_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.max_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.max_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.avgr_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.eq (local.get $v) (local.get $v)))
      (local.set $v (i8x16.ne (local.get $v) (local.get $v)))
      (local.set $v (i8x16.lt_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.lt_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.le_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.gt_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.ge_u (local.get $v) (local.get $v)))
      (local.set $v (i8x16.abs (local.get $v)))
      (local.set $v (i8x16.neg (local.get $v)))
      (local.set $v (i8x16.popcnt (local.get $v)))
      (local.set $v (i8x16.shl (local.get $v) (i32.const 1)))
      (local.set $v (i8x16.shr_s (local.get $v) (local.get $s)))
      (local.set $v (i8x16.shr_u (local.get $v) (i32.const 2)))
      (local.set $v (i8x16.swizzle (local.get $v) (local.get $v)))
      (local.set $v (i8x16.narrow_i16x8_s (local.get $v) (local.get $v)))
      (local.set $v (i8x16.narrow_i16x8_u (local.get $v) (local.get $v)))
      (local.set $s (i8x16.extract_lane_s 0 (local.get $v)))
      (local.set $s (i8x16.extract_lane_u 1 (local.get $v)))
      (local.set $v (i8x16.replace_lane 2 (local.get $v) (local.get $s)))
      (local.set $s (i8x16.all_true (local.get $v)))
      (local.set $s (i8x16.bitmask (local.get $v)))
      (local.set $v (i8x16.shuffle 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
        (local.get $v) (local.get $v)))
      ;; i16x8
      (local.set $v (i16x8.add (local.get $v) (local.get $v)))
      (local.set $v (i16x8.sub (local.get $v) (local.get $v)))
      (local.set $v (i16x8.mul (local.get $v) (local.get $v)))
      (local.set $v (i16x8.add_sat_s (local.get $v) (local.get $v)))
      (local.set $v (i16x8.add_sat_u (local.get $v) (local.get $v)))
      (local.set $v (i16x8.min_s (local.get $v) (local.get $v)))
      (local.set $v (i16x8.max_u (local.get $v) (local.get $v)))
      (local.set $v (i16x8.avgr_u (local.get $v) (local.get $v)))
      (local.set $v (i16x8.q15mulr_sat_s (local.get $v) (local.get $v)))
      (local.set $v (i16x8.eq (local.get $v) (local.get $v)))
      (local.set $v (i16x8.lt_u (local.get $v) (local.get $v)))
      (local.set $v (i16x8.abs (local.get $v)))
      (local.set $v (i16x8.neg (local.get $v)))
      (local.set $v (i16x8.shl (local.get $v) (local.get $s)))
      (local.set $v (i16x8.shr_s (local.get $v) (i32.const 1)))
      (local.set $v (i16x8.shr_u (local.get $v) (local.get $s)))
      (local.set $s (i16x8.extract_lane_s 0 (local.get $v)))
      (local.set $s (i16x8.extract_lane_u 1 (local.get $v)))
      (local.set $v (i16x8.replace_lane 2 (local.get $v) (local.get $s)))
      (local.set $s (i16x8.all_true (local.get $v)))
      (local.set $s (i16x8.bitmask (local.get $v)))
      (local.set $v (i16x8.narrow_i32x4_s (local.get $v) (local.get $v)))
      (local.set $v (i16x8.narrow_i32x4_u (local.get $v) (local.get $v)))
      (local.set $v (i16x8.extadd_pairwise_i8x16_s (local.get $v)))
      (local.set $v (i16x8.extadd_pairwise_i8x16_u (local.get $v)))
      (local.set $v (i16x8.extend_low_i8x16_s (local.get $v)))
      (local.set $v (i16x8.extend_high_i8x16_u (local.get $v)))
      (local.set $v (i16x8.extmul_low_i8x16_s (local.get $v) (local.get $v)))
      (local.set $v (i16x8.extmul_high_i8x16_u (local.get $v) (local.get $v)))
      ;; i32x4
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.sub (local.get $v) (local.get $v)))
      (local.set $v (i32x4.mul (local.get $v) (local.get $v)))
      (local.set $v (i32x4.min_s (local.get $v) (local.get $v)))
      (local.set $v (i32x4.max_u (local.get $v) (local.get $v)))
      (local.set $v (i32x4.eq (local.get $v) (local.get $v)))
      (local.set $v (i32x4.lt_s (local.get $v) (local.get $v)))
      (local.set $v (i32x4.abs (local.get $v)))
      (local.set $v (i32x4.neg (local.get $v)))
      (local.set $v (i32x4.shl (local.get $v) (local.get $s)))
      (local.set $v (i32x4.shr_s (local.get $v) (i32.const 1)))
      (local.set $v (i32x4.shr_u (local.get $v) (local.get $s)))
      (local.set $s (i32x4.extract_lane 0 (local.get $v)))
      (local.set $v (i32x4.replace_lane 1 (local.get $v) (local.get $s)))
      (local.set $s (i32x4.all_true (local.get $v)))
      (local.set $s (i32x4.bitmask (local.get $v)))
      (local.set $v (i32x4.dot_i16x8_s (local.get $v) (local.get $v)))
      (local.set $v (i32x4.extadd_pairwise_i16x8_s (local.get $v)))
      (local.set $v (i32x4.extend_low_i16x8_s (local.get $v)))
      (local.set $v (i32x4.extend_high_i16x8_u (local.get $v)))
      (local.set $v (i32x4.extmul_low_i16x8_s (local.get $v) (local.get $v)))
      (local.set $v (i32x4.extmul_high_i16x8_u (local.get $v) (local.get $v)))
      ;; i64x2
      (local.set $v (i64x2.add (local.get $v) (local.get $v)))
      (local.set $v (i64x2.sub (local.get $v) (local.get $v)))
      (local.set $v (i64x2.mul (local.get $v) (local.get $v)))
      (local.set $v (i64x2.eq (local.get $v) (local.get $v)))
      (local.set $v (i64x2.lt_s (local.get $v) (local.get $v)))
      (local.set $v (i64x2.abs (local.get $v)))
      (local.set $v (i64x2.neg (local.get $v)))
      (local.set $v (i64x2.shl (local.get $v) (local.get $s)))
      (local.set $v (i64x2.shr_s (local.get $v) (i32.const 1)))
      (local.set $v (i64x2.shr_u (local.get $v) (local.get $s)))
      (local.set $s (i32.wrap_i64 (i64x2.extract_lane 0 (local.get $v))))
      (local.set $v (i64x2.replace_lane 1 (local.get $v) (i64.extend_i32_s (local.get $s))))
      (local.set $s (i64x2.all_true (local.get $v)))
      (local.set $s (i64x2.bitmask (local.get $v)))
      (local.set $v (i64x2.extend_low_i32x4_s (local.get $v)))
      (local.set $v (i64x2.extend_high_i32x4_u (local.get $v)))
      (local.set $v (i64x2.extmul_low_i32x4_s (local.get $v) (local.get $v)))
      (local.set $v (i64x2.extmul_high_i32x4_u (local.get $v) (local.get $v)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )

  ;; ---- SIMD: float lanes, bitwise, conversions, loads/stores ----------------
  (func (export "torture_simd_float")
    (local $i i32) (local $v v128) (local $f f32) (local $d f64) (local $s i32)
    (local.set $i (i32.const 50000))
    (local.set $v (v128.const f32x4 1 2 3 4))
    (loop $l
      (local.set $s (i32.and (local.get $i) (i32.const 7)))
      ;; f32x4
      (local.set $v (f32x4.add (local.get $v) (local.get $v)))
      (local.set $v (f32x4.sub (local.get $v) (local.get $v)))
      (local.set $v (f32x4.mul (local.get $v) (local.get $v)))
      (local.set $v (f32x4.div (local.get $v) (local.get $v)))
      (local.set $v (f32x4.min (local.get $v) (local.get $v)))
      (local.set $v (f32x4.max (local.get $v) (local.get $v)))
      (local.set $v (f32x4.pmin (local.get $v) (local.get $v)))
      (local.set $v (f32x4.pmax (local.get $v) (local.get $v)))
      (local.set $v (f32x4.eq (local.get $v) (local.get $v)))
      (local.set $v (f32x4.ne (local.get $v) (local.get $v)))
      (local.set $v (f32x4.lt (local.get $v) (local.get $v)))
      (local.set $v (f32x4.le (local.get $v) (local.get $v)))
      (local.set $v (f32x4.abs (local.get $v)))
      (local.set $v (f32x4.neg (local.get $v)))
      (local.set $v (f32x4.sqrt (local.get $v)))
      (local.set $v (f32x4.ceil (local.get $v)))
      (local.set $v (f32x4.floor (local.get $v)))
      (local.set $v (f32x4.trunc (local.get $v)))
      (local.set $v (f32x4.nearest (local.get $v)))
      (local.set $f (f32x4.extract_lane 0 (local.get $v)))
      (local.set $v (f32x4.replace_lane 1 (local.get $v) (local.get $f)))
      ;; f64x2
      (local.set $v (f64x2.add (local.get $v) (local.get $v)))
      (local.set $v (f64x2.mul (local.get $v) (local.get $v)))
      (local.set $v (f64x2.div (local.get $v) (local.get $v)))
      (local.set $v (f64x2.min (local.get $v) (local.get $v)))
      (local.set $v (f64x2.pmax (local.get $v) (local.get $v)))
      (local.set $v (f64x2.eq (local.get $v) (local.get $v)))
      (local.set $v (f64x2.lt (local.get $v) (local.get $v)))
      (local.set $v (f64x2.abs (local.get $v)))
      (local.set $v (f64x2.neg (local.get $v)))
      (local.set $v (f64x2.sqrt (local.get $v)))
      (local.set $v (f64x2.ceil (local.get $v)))
      (local.set $v (f64x2.nearest (local.get $v)))
      (local.set $d (f64x2.extract_lane 0 (local.get $v)))
      (local.set $v (f64x2.replace_lane 1 (local.get $v) (local.get $d)))
      ;; conversions between lane types
      (local.set $v (f32x4.convert_i32x4_s (local.get $v)))
      (local.set $v (f32x4.convert_i32x4_u (local.get $v)))
      (local.set $v (i32x4.trunc_sat_f32x4_s (local.get $v)))
      (local.set $v (i32x4.trunc_sat_f32x4_u (local.get $v)))
      (local.set $v (f64x2.convert_low_i32x4_s (local.get $v)))
      (local.set $v (i32x4.trunc_sat_f64x2_s_zero (local.get $v)))
      (local.set $v (f32x4.demote_f64x2_zero (local.get $v)))
      (local.set $v (f64x2.promote_low_f32x4 (local.get $v)))
      ;; v128 bitwise + boolean
      (local.set $v (v128.and (local.get $v) (local.get $v)))
      (local.set $v (v128.or (local.get $v) (local.get $v)))
      (local.set $v (v128.xor (local.get $v) (local.get $v)))
      (local.set $v (v128.andnot (local.get $v) (local.get $v)))
      (local.set $v (v128.not (local.get $v)))
      (local.set $v (v128.bitselect (local.get $v) (local.get $v) (local.get $v)))
      (drop (v128.any_true (local.get $v)))
      ;; v128 load/store variants
      (v128.store (i32.const 0) (local.get $v))
      (local.set $v (v128.load (i32.const 0)))
      (local.set $v (v128.load8x8_s (i32.const 0)))
      (local.set $v (v128.load16x4_u (i32.const 0)))
      (local.set $v (v128.load32x2_s (i32.const 0)))
      (local.set $v (v128.load8_splat (i32.const 0)))
      (local.set $v (v128.load16_splat (i32.const 0)))
      (local.set $v (v128.load32_splat (i32.const 0)))
      (local.set $v (v128.load64_splat (i32.const 0)))
      (local.set $v (v128.load32_zero (i32.const 0)))
      (local.set $v (v128.load64_zero (i32.const 0)))
      (local.set $v (v128.load8_lane 0 (i32.const 0) (local.get $v)))
      (local.set $v (v128.load16_lane 1 (i32.const 0) (local.get $v)))
      (local.set $v (v128.load32_lane 2 (i32.const 0) (local.get $v)))
      (local.set $v (v128.load64_lane 1 (i32.const 0) (local.get $v)))
      (v128.store8_lane 0 (i32.const 0) (local.get $v))
      (v128.store16_lane 1 (i32.const 0) (local.get $v))
      (v128.store32_lane 2 (i32.const 0) (local.get $v))
      (v128.store64_lane 1 (i32.const 0) (local.get $v))
      ;; splats
      (local.set $v (i8x16.splat (local.get $s)))
      (local.set $v (i16x8.splat (local.get $s)))
      (local.set $v (i32x4.splat (local.get $s)))
      (local.set $v (i64x2.splat (i64.extend_i32_s (local.get $s))))
      (local.set $v (f32x4.splat (local.get $f)))
      (local.set $v (f64x2.splat (local.get $d)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br_if $l (local.get $i))
    )
  )
)

(assert_return (invoke "torture_i32"))
(assert_return (invoke "torture_i64"))
(assert_return (invoke "torture_f32"))
(assert_return (invoke "torture_f64"))
(assert_return (invoke "torture_conv"))
(assert_return (invoke "torture_load"))
(assert_return (invoke "torture_store"))
(assert_return (invoke "torture_memory_size"))
(assert_return (invoke "torture_memory_copy"))
(assert_return (invoke "torture_memory_fill"))
(assert_return (invoke "torture_memory_init"))
(assert_return (invoke "torture_table_get"))
(assert_return (invoke "torture_table_set"))
(assert_return (invoke "torture_table_size"))
(assert_return (invoke "torture_table_copy"))
(assert_return (invoke "torture_table_fill"))
(assert_return (invoke "torture_table_init"))
(assert_return (invoke "torture_ref"))
(assert_return (invoke "torture_global_get"))
(assert_return (invoke "torture_global_set"))
(assert_return (invoke "torture_param_var"))
(assert_return (invoke "torture_call"))
(assert_return (invoke "torture_call_indirect"))
(assert_return (invoke "torture_br_table"))
(assert_return (invoke "torture_return_call" (i32.const 1000000)))
(assert_return (invoke "torture_return_call_indirect" (i32.const 1000000)) (i32.const 0))
(assert_return (invoke "torture_simd_int"))
(assert_return (invoke "torture_simd_float"))
